x-common-build: &common-build
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - "./src:/app"
  env_file:
    - ./src/.env

services:
  web:
    <<: *common-build
    command: >
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./src/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    <<: *common-build
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis

  celery_beat:
    <<: *common-build
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis

volumes:
    postgres_data:
    redis_data:

